config/routes.rb
DatabaseProject::Application.routes.draw do
  resources :groups

  resources :pages

  resources :users
  get "main/like_p"
  get "main/forgotpassword"
  post "main/forgotpassword"
  get "main/friends"
  get "question/index"
  get "check/add"
  post "groups/add_member"
  post "groups/leave_member"
  post "groups/add_request"
  post "groups/delete_request"
  get "main/editprofile"
  post "main/updateinfo"
  post "main/updateinfo2"
  get "check/index"
  get "question/delete"
  post "main/add_messages"
  get "api/index"
  get "main/profile2"
  get "pages/create"
  post "pages/submit"
  post "groups/submit"
  post "groups/comment"
  get "main/messages"
  post "main/messages"
   post "main/post_submit"
   post "main/add_comment"
   post "main/like_comment"
   post "main/like_post"
  post "pages/add"
  get "pages/add"
  get "pages/show"
  get "question/ask"
  post "question/ask"
  get "question/addAnswer"
  post "question/addAnswer"
  get "question/upvote"
  post "question/upvote"
  get "question/downvote"
  post "question/downvote"
  get "question/addAnswer"
  post "question/addAnswer"
  get "question/edit"
  post "question/edit"
  get "question/update"
  post "question/update"
  get "question/myquestions"
  post "question/myquestions"
  get "question/add"
  post "question/add"
  post "pages/comment"
  get "question/view"
  post "question/view"
  get "main/index"
  get "main/profile"
  post "main/index"
  get "main/logout"
  post "main/logout"
  get "main/update"
  post "main/update"
  post "main/profile"
  post "main/confirm"
  get "main/confirm"
  post "pages/pageLike"
   post "main/manageFriends"
  get "main/manageFriends"
  get "main/FriendRequests"

  root 'main#index'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/cookie_check.rb
class CookieCheck < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_attached_file :timeline_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :timeline_pic, :content_type => /\Aimage\/.*\Z/
    has_many :group_members, dependent: :destroy
    has_many :group_requests, dependent: :destroy
end

app/models/group_comment.rb
class GroupComment < ActiveRecord::Base
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
    belongs_to   :groups
end

app/models/group_post.rb
class GroupPost < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
    has_attached_file :profile_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :profile_pic, :content_type => /\Aimage\/.*\Z/
    has_attached_file :timeline_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :timeline_pic, :content_type => /\Aimage\/.*\Z/
end

app/models/pages_like.rb
class PagesLike < ActiveRecord::Base
end

app/models/pages_post.rb
class PagesPost < ActiveRecord::Base
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers, dependent: :destroy
	has_many :question_tags, dependent:	:destroy
end

app/models/question_tag.rb
class QuestionTag < ActiveRecord::Base
	belongs_to 	:questions
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many  :question_tags,dependent: :destroy
	has_many 	:questions, :through => :question_tags,dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
    has_attached_file :profile_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :profile_pic, :content_type => /\Aimage\/.*\Z/
    has_attached_file :timeline_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :timeline_pic, :content_type => /\Aimage\/.*\Z/
end

app/models/wall_post.rb
class WallPost < ActiveRecord::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    if cookies[:user_id]!="4"
      redirect_to action: "profile",controller: "main"
    end
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def submit
    if params[:post]==""
      redirect_to action: "show", id: $global_id, error_post: "empty post"
    else
      new_post  = GroupPost.new
      new_post.content = params[:post]
      new_post.group_id = $global_id
      new_post.user_id = cookies[:user_id]
      new_post.save
      redirect_to action: "show", id: $global_id
    end
  end
  def comment
    if params[:comment]!=""
      new_comment = GroupComment.new
      new_comment.added_by = cookies[:user_id]
      new_comment.comment = params[:comment]
      new_comment.post_id = params[:post_id]
      new_comment.save
    end
    redirect_to action: "show",id: $global_id
  end
  def show
    begin
      $global_id = params[:id]
     
      @group_posts = GroupPost.find_by_sql("select * from group_posts where group_id="+params[:id])
    rescue
      redirect_to action: "profile",controller: "main"
    end
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def add_member
    @g = Group.find(params[:id])
    if @g.privacy == "public" 
      @n = GroupMember.new
      @n.group_id = params[:id]
      @n.user_id = cookies[:user_id]
      @n.save
      @g.group_members << @n
    else
      @n = GroupRequest.new
      @n.group_id = params[:id]
      @n.user_id = cookies[:user_id]
      @n.save
      @g.group_requests << @n
    end
    redirect_to action: "show", id: params[:id]
  end
  def leave_member
    GroupMember.where(:user_id => cookies[:user_id],:group_id => params[:id])[0].destroy
    redirect_to action: "show", id: params[:id]
  end
  def create
    @group = Group.new(group_params)
    @group.timeline_pic = params[:group][:timeline_pic]
    @group.admin_id = cookies[:user_id]
    
    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
        @g = GroupMember.new
        @g.group_id = @group.id
        @g.user_id = cookies[:user_id]
        @g.save
        @group.group_members << @g
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end
def add_request
  @n = GroupMember.new
  @n.user_id = params[:new_user_id]
  @n.group_id = params[:id]
  @n.save
  @g = Group.find(params[:id])
  @g.group_members <<  @n
  GroupRequest.where(:user_id => params[:new_user_id],:group_id => params[:id])[0].destroy
  redirect_to action: "show", id: params[:id]
end
def delete_request
  GroupRequest.where(:user_id => params[:new_user_id],:group_id => params[:id])[0].destroy
  redirect_to action: "show", id: params[:id]
end
  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :privacy, :admin_id,:timeline_pic)
    end
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm">
        <%= form_for(@group) do |form| %>
          <fieldset>
          
          <div class="form-group">
               <label class="col-md-3 control-label" for="email">Group Name</label>
                <div class="col-md-9">
              <%= form.text_field :name,:class=>"form-control" %>
             </div>
            </div>
          
          <div class="form-group">
                <label class="col-md-3 control-label" for="message">Description</label>
                 <div class="col-md-9">
                <%= form.text_area :description ,:class=>"form-control",:rows=>"5"%>
            </div>
            </div>
          
          <div class="form-group">
                  <label class="col-md-3 control-label" for="Gender">Privacy</label>
                  <div class="col-md-9">
                      <select id="group[privacy]" name="group[privacy]"  class="form-control">
                            <option value="private"  >Private</option>
                                                  <option value="public" >Public</option>
                                                  
                                                </select>
                                              </div>
                                            </div> 
          
          <div class="form-group">
                <label class="col-md-3 control-label" for="message">Pic</label>
                 <div class="col-md-9">
          <%= form.file_field :timeline_pic %>
          </div>
            </div>

            <div class="form-group">
              <div class="col-md-12 text-right">
           <%= form.submit 'Create',:class=>"btn btn-default btn-info btn-lg btn-block" %>
           </div>
            </div>

          </fieldset>
        <% end %>
    </div>
  </div>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<h1>Listing groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Privacy</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.privacy %></td>
        <td><%= group.admin_id %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
 <div> 
      <div style="float:left;width:20%;">

            <div style="padding:5px;margin:10px;" class="row">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Profile </h3>
                    </div>
                    <div class="panel-body">
                        <% user= User.find(cookies[:user_id])%>
                        <%= image_tag  user.profile_pic.url(:thumb), class: "img-circle", :height => "100",:width => "100" %><br/>
                        

                        <h4><%= user.fname + " " + user.lname %></h4>
                        <a href="/main/profile"><%= cookies[:fname] %></a><br/>
                        <a href="/main/editprofile" class="btn btn-default btn-info btn-xs btn-block"><span class="glyphicon glyphicon-cog"></span> <b>Edit Profile</b></a>
                       
                        <a href="/main/logout" class="btn btn-default btn-info btn-xs btn-block"><span class="glyphicon glyphicon-off"></span> <b>Logout</b></a>

                        
                    </div>
                </div>
            </div>
            <hr>
      
            <ul class="list-unstyled">
              <li class="nav-header">
              <a href="#" data-toggle="collapse" data-target="#menu3">
                <h5>Groups<i class="glyphicon glyphicon-chevron-right"></i></h5>
                </a>
              
                  <ul class="list-unstyled collapse" id="menu3">
                      <% my_groups = GroupMember.where(:user_id => cookies[:user_id]) %>
                      <% for groups in my_groups %>
                        <% g = Group.find(groups.group_id) %>
                      <li><a href=<%='/groups/'+g.id.to_s %>><i class="glyphicon glyphicon-circle"></i> <%= g.name %></a></li>
                      <% end %>
                  </ul>
              </li>
              <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#userMenu">
                  
                  <ul class="list-unstyled collapse in" id="userMenu">
                      <li class="active"> <a href="/main/profile"><i class="glyphicon glyphicon-home"></i> Home</a></li>
                      <li><a href="/main/messages"><i class="glyphicon glyphicon-envelope"></i> Messages <span class="badge badge-info"></span></a></li>
                      <li><a href="/pages/new"><i class="glyphicon glyphicon-cog"></i> Create Page</a></li>
                      <li><a href="/groups/new"><i class="glyphicon glyphicon-cog"></i> Create group</a></li>
                      <li><a href="/main/friends"><i class="glyphicon glyphicon-user"></i> Friends <span class="badge badge-info"><%=Friend.find(:all, :conditions => { :user1 => cookies[:user_id] }).count%></span></a></li>
                  </ul>
              
              
            </ul>
                 
            <hr>

            
      </div>
      <div style="float:left;width:55%;padding:5px;margin:5px">
            <div style="padding:10px;">
                  <input id ="autocomplete" type="text" class="form-control" placeholder="Search"> 
            </div>

            <div style="heigth:300px;">
              <%= image_tag  @group.timeline_pic.url, :height => "250",:width => "650"  %>
            </div>
              <div style="padding:10px;margin:5px;width:45%;float:left">
                <% user= User.find(cookies[:user_id])%>
                <% if GroupMember.where(:user_id => user.id, :group_id => @group.id)[0]!=nil %>
                <%= form_tag "/groups/submit" do %>
   
                  <label for="text"></label> <textarea id="text"  name="post"  rows="3" cols="35" class="required"></textarea>
                 <br/>
                 <%= params[:error_post] %> <br/>
                  <input type="submit" value="Post"/>
                  
              <%end%>
              <% end %>
            </div>
              
              <% for post in @group_posts %>
                <div class="WallPost" id='<%= post.id.to_s+"wall_post"%>' style="background-color:aquamarine;margin:10px;width:45%;float:left" >
                      <div style="background-color:pink">
                          <% post_by = User.find(post.user_id) %>
                          <div style="float:left;width:20%;">
                                <%= image_tag  post_by.profile_pic.url(:thumb),size: "50x50" %>
                          </div>
                          <div>
                              <p>
                                <h4><%= post_by.fname + " " + post_by.lname + ' on '%></h4> 
                                      <%= "on " + post.created_at.to_formatted_s %> 
                              </p>
                          </div>
                      </div>
                            <br/>
                      <div>
                          <p>
                              <%= post.content %>
                          </p>
                         
                      </div>
                             
                      <div style="background-color: white; padding-top:5px;padding-left:5px;padding-bottom:5px;padding-right:5px;">
                          <% comments = GroupComment.find_by_sql("select * from group_comments where post_id="+post.id.to_s) %>

                          <% for comment in comments %>

                              <div style="background-color: grey;padding-top:5px;padding-left:5px;padding-bottom:5px;padding-right:5px;margin-bottom:5px">
                                  <% comment_by = User.find(comment.added_by) %>
                                  <%= image_tag  comment_by.profile_pic.url(:thumb),size: "40x40",class: "img-circle" %>
                                  <%= comment.comment%><br/>
                                  
                              </div>
                          <% end %>
                              <%= form_tag "/groups/comment" do %>
                                   <label for="text"></label> <textarea id="text"name="comment" ></textarea>
                                   <%= hidden_field_tag 'post_id', post.id %>
                                   <input type="submit" value="comment"/> 
                              <%end%>
                      </div>
                  </div>
              <%end%> 
                
      </div>
      <div style="padding:20px;">
                
      </div>
  </div>



  <div>



<%if @group.admin_id.to_s==cookies[:user_id].to_s %>
<%= link_to 'Edit', edit_group_path(@group) %> 
<% end %>
<% if GroupRequest.where(:user_id => cookies[:user_id],:group_id => @group.id)[0]!=nil%>
<%= button_to  "cancel request", {:action => "delete_request",  :id => params[:id],:new_user_id => cookies[:user_id]},:class => 'btn btn-default btn-warning btn-sm' %>
<% elsif GroupMember.where(:user_id => cookies[:user_id],:group_id => @group.id)[0]==nil  %>
    
<%= button_to  "join group", {:action => "add_member",  :id => params[:id]},:class => 'btn btn-default btn-success btn-sm' %>
<%elsif @group.admin_id.to_s!=cookies[:user_id].to_s %>
  <%= button_to  "leave group", {:action => "leave_member",  :id => params[:id]},:class => 'btn btn-default btn-danger btn-sm' %>
<% end %>

<div class="bs-example">
    <div class="panel-group" id="accordion">

  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Description</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <p><%= @group.description%></p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Members</a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <p>
            <% members = @group.group_members %>
            <% for n in members %>
            
                    <% user_new = User.find(n.user_id) %>
                    <a href= <%= "/main/profile?id="+user_new.id.to_s %> > <%= image_tag  user_new.profile_pic.url, :height => "50",:width => "50" %></a>
                 
            <% end %>

          
        </p>
      </div>
    </div>
  </div>
  <% if @group.admin_id.to_s == cookies[:user_id].to_s %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">New Member Requests</a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <p>
          <table>
            <% new_request = @group.group_requests %>
            <% for n in new_request %>
            <tr>
                <td>
                    <% user_new = User.find(n.user_id) %>
                    <a href= <%= "/main/profile?id="+user_new.id.to_s %> > <%= image_tag  user_new.profile_pic.url, :height => "50",:width => "50" %></a>
                  </td>
                  <td>
                      <h5><%='  ' + user_new.fname%> </h5>
                  </td>
                  <td>
                      <%= button_to  "Add", {:action => "add_request",  :id => params[:id],:new_user_id => user_new.id},:class => 'btn btn-default btn-success btn-sm' %>
                  </td>
                  <td>
                     <%= button_to  "Delete", {:action => "delete_request",  :id => params[:id],:new_user_id => user_new.id},:class => 'btn btn-default btn-danger btn-sm' %>
                  </td>
            </tr>
            <% end %>
          </table>
        </p>
      </div>
    </div>
  </div>
  <%end %>

  
</div>
</div>
  </div>
















 