config/routes.rb
DatabaseProject::Application.routes.draw do
  resources :groups

  resources :pages

  resources :users
  get "main/like_p"
  get "main/forgotpassword"
  post "main/forgotpassword"
  get "main/friends"
  get "question/index"
  get "check/add"
  post "groups/add_member"
  post "groups/leave_member"
  post "groups/add_request"
  post "groups/delete_request"
  get "main/editprofile"
  post "main/updateinfo"
  post "main/updateinfo2"
  get "check/index"
  get "question/delete"
  post "main/add_messages"
  get "api/index"
  get "main/profile2"
  get "pages/create"
  post "pages/submit"
  post "groups/submit"
  post "groups/comment"
  get "main/messages"
  post "main/messages"
   post "main/post_submit"
   post "main/add_comment"
   post "main/like_comment"
   post "main/like_post"
  post "pages/add"
  get "pages/add"
  get "pages/show"
  get "question/ask"
  post "question/ask"
  get "question/addAnswer"
  post "question/addAnswer"
  get "question/upvote"
  post "question/upvote"
  get "question/downvote"
  post "question/downvote"
  get "question/addAnswer"
  post "question/addAnswer"
  get "question/edit"
  post "question/edit"
  get "question/update"
  post "question/update"
  get "question/myquestions"
  post "question/myquestions"
  get "question/add"
  post "question/add"
  post "pages/comment"
  get "question/view"
  post "question/view"
  get "main/index"
  get "main/profile"
  post "main/index"
  get "main/logout"
  post "main/logout"
  get "main/update"
  post "main/update"
  post "main/profile"
  post "main/confirm"
  get "main/confirm"
  post "pages/pageLike"
   post "main/manageFriends"
  get "main/manageFriends"
  get "main/FriendRequests"

  root 'main#index'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/cookie_check.rb
class CookieCheck < ActiveRecord::Base
end

app/models/friend.rb
class Friend < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_attached_file :timeline_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :timeline_pic, :content_type => /\Aimage\/.*\Z/
    has_many :group_members, dependent: :destroy
    has_many :group_requests, dependent: :destroy
end

app/models/group_member.rb
class GroupMember < ActiveRecord::Base
    belongs_to   :groups
end

app/models/group_post.rb
class GroupPost < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
    has_attached_file :profile_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :profile_pic, :content_type => /\Aimage\/.*\Z/
    has_attached_file :timeline_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :timeline_pic, :content_type => /\Aimage\/.*\Z/
end

app/models/pages_like.rb
class PagesLike < ActiveRecord::Base
end

app/models/pages_post.rb
class PagesPost < ActiveRecord::Base
end

app/models/post_comment.rb
class PostComment < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers, dependent: :destroy
	has_many :question_tags, dependent:	:destroy
end

app/models/question_tag.rb
class QuestionTag < ActiveRecord::Base
	belongs_to 	:questions
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many  :question_tags,dependent: :destroy
	has_many 	:questions, :through => :question_tags,dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
    has_attached_file :profile_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :profile_pic, :content_type => /\Aimage\/.*\Z/
    has_attached_file :timeline_pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :timeline_pic, :content_type => /\Aimage\/.*\Z/
end

app/models/wall_post.rb
class WallPost < ActiveRecord::Base
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>DatabaseProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.0.min.js"></script>
  <script type="text/javascript" src="/jquerya/dist/jquery.autocomplete.js"></script>
  <link type="text/css" rel="stylesheet" href="/css/stylish_div.css" />
  <link type="text/css" rel="stylesheet" href="/css/mycss.css" />
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="/bootstrap/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="/bootstrap/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="/bootstrap/js/bootstrap.min.js"></script>



  <%= csrf_meta_tags %>
    <script>
    $(document).ready(function() {

     //var a = $('#autocomplete').text(); 
     $('#autocomplete').autocomplete({
    serviceUrl: '/api/index',
    params:{"query":$('#autocomplete').text()},
    onSelect: function (suggestion) {
        window.location.replace(suggestion.link);
    }
});
    });
</script>
  <style type="text/css">
            body {
  padding-top:50px;
}

#masthead {
  min-height:250px;
}

#masthead h1 {
  font-size: 30px;
  line-height: 1;
    padding-top:20px;
}

#masthead .well {
  margin-top:8%;
}

@media screen and (min-width: 768px) {
  #masthead h1 {
    font-size: 50px;
  }
}

.navbar-bright {
  background-color:#111155;
    color:#fff;
}

.affix-top,.affix{
  position: static;
}

@media (min-width: 979px) {
  #sidebar.affix-top {
    position: static;
    margin-top:30px;
    width:228px;
  }
  
  #sidebar.affix {
    position: fixed;
    top:70px;
    width:228px;
  }
}

#sidebar li.active {
    border:0 #eee solid;
    border-right-width:4px;
}

        </style>
        <style type="text/css">
            .navbar-static-top {
  margin-bottom:20px;
}

i {
  font-size:16px;
}

.nav > li > a {
  color:#787878;
}
  
footer {
  margin-top:20px;
  padding-top:20px;
  padding-bottom:20px;
  background-color:#efefef;
}

/* count indicator near icons */
.nav>li .count {
  position: absolute;
  bottom: 12px;
  right: 6px;
  font-size: 10px;
  font-weight: normal;
  background: rgba(51,200,51,0.55);
  color: rgba(255,255,255,0.9);
  line-height: 1em;
  padding: 2px 4px;
  -webkit-border-radius: 10px;
  -moz-border-radius: 10px;
  -ms-border-radius: 10px;
  -o-border-radius: 10px;
  border-radius: 10px;
}

/* indent 2nd level */
.list-unstyled li > ul > li {
   margin-left:10px;
   padding:8px;
}
        </style>
</head>

<body >


<%= yield %>

</body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DatabaseProject</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div class="dialog">
    	<a href="/main/profile"><%= cookies[:user_name] %></a>
		<a href="/question/ask">Ask Question</a>
		<a href="/question/myquestions">My Question</a>
		<a href="/main/logout">logout</a>
  	</div>
	

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm">
        <%= form_for(@page) do |form|%>
          <fieldset>
          
          <div class="form-group">
               <label class="col-md-3 control-label" for="email">Title</label>
                <div class="col-md-9">
              <%= form.text_field :title,:class=>"form-control" %>
             </div>
            </div>
          
          <div class="form-group">
                <label class="col-md-3 control-label" for="message">Description</label>
                 <div class="col-md-9">
                <%= form.text_area :description ,:class=>"form-control",:rows=>"5"%>
            </div>
            </div>
          
          
          <div class="form-group">
                <label class="col-md-3 control-label" for="message">Pic</label>
                 <div class="col-md-9">
          <%= form.file_field :timeline_pic %>
          </div>
            </div>

            <div class="form-group">
              <div class="col-md-12 text-right">
           <%= form.submit 'Save',:class=>"btn btn-default btn-info btn-lg btn-block" %>
           </div>
            </div>

          </fieldset>
        <% end %>
    </div>
  </div>
  </div>
</div>

app/views/pages/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Like</th>
      <th>Privacy</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.description %></td>
        <td><%= page.like %></td>
        <td><%= page.privacy %></td>
        <td><%= page.admin_id %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<div class="container">
	<div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well well-sm">
				<%= form_for @page, :url => pages_path, :html => { :multipart => true , :class => "form-horizontal"} do |form| %>
					<fieldset>
					
					<div class="form-group">
				       <label class="col-md-3 control-label" for="email">Title</label>
				        <div class="col-md-9">
							<%= form.text_field :title,:class=>"form-control" %>
					 	 </div>
				    </div>
					
					<div class="form-group">
				        <label class="col-md-3 control-label" for="message">Description</label>
				         <div class="col-md-9">
								<%= form.text_area :description ,:class=>"form-control",:rows=>"5"%>
						</div>
				    </div>
					
				  
				  <div class="form-group">
				        <label class="col-md-3 control-label" for="message">Pic</label>
				         <div class="col-md-9">
				  <%= form.file_field :timeline_pic %>
				  </div>
				    </div>

				    <div class="form-group">
              <div class="col-md-12 text-right">
				   <%= form.submit 'Create',:class=>"btn btn-default btn-info btn-lg btn-block" %>
				   </div>
            </div>

				  </fieldset>
				<% end %>
 		</div>
 	</div>
	</div>
</div>

app/views/pages/show.html.erb
 <div> 
      <div style="float:left;width:20%;">

            <div style="padding:5px;margin:10px;" class="row">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Profile </h3>
                    </div>
                    <div class="panel-body">
                        <% user= User.find(cookies[:user_id])%>
                        <%= image_tag  user.profile_pic.url(:thumb), class: "img-circle", :height => "40%",:width => "80%" %><br/>
                        

                        <h4><%= user.fname + " " + user.lname %></h4>
                        <a href="/main/profile"><%= cookies[:fname] %></a><br/>
                        <a href="/main/editprofile" class="btn btn-default btn-info btn-xs btn-block"><span class="glyphicon glyphicon-cog"></span> <b>Edit Profile</b></a>
                       
                        <a href="/main/logout" class="btn btn-default btn-info btn-xs btn-block"><span class="glyphicon glyphicon-off"></span> <b>Logout</b></a>

                        
                    </div>
                </div>
            </div>
            <hr>
      
            <ul class="list-unstyled">
              <li class="nav-header">
              <a href="#" data-toggle="collapse" data-target="#menu3">
                <h5>Groups<i class="glyphicon glyphicon-chevron-right"></i></h5>
                </a>
              
                  <ul class="list-unstyled collapse" id="menu3">
                      <% my_groups = GroupMember.where(:user_id => cookies[:user_id]) %>
                      <% for groups in my_groups %>
                        <% g = Group.find(groups.group_id) %>
                      <li><a href=<%='/groups/'+g.id.to_s %>><i class="glyphicon glyphicon-circle"></i> <%= g.name %></a></li>
                      <% end %>
                  </ul>
              </li>
              <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#userMenu">
                  
                  <ul class="list-unstyled collapse in" id="userMenu">
                      <li class="active"> <a href="/main/profile"><i class="glyphicon glyphicon-home"></i> Home</a></li>
                      <li><a href="/main/messages"><i class="glyphicon glyphicon-envelope"></i> Messages <span class="badge badge-info"></span></a></li>
                      <li><a href="/pages/new"><i class="glyphicon glyphicon-cog"></i> Create Page</a></li>
                      <li><a href="/groups/new"><i class="glyphicon glyphicon-cog"></i> Create group</a></li>
                      <li><a href="/main/friends"><i class="glyphicon glyphicon-user"></i> Friends <span class="badge badge-info"><%=Friend.find(:all, :conditions => { :user1 => cookies[:user_id] }).count%></span></a></li>
                  </ul>
              
              
            </ul>
                 
            <hr>

            
      </div>
      <div style="float:left;width:55%;padding:5px;margin:5px">
            <div style="padding:10px;">
                  <input id ="autocomplete" type="text" class="form-control" placeholder="Search"> 
            </div>

            <div style="heigth:300px;">
              <h2> <%=@page.title %> </h2>
              <br/>
              <%= image_tag  @page.timeline_pic.url, :height => "250",:width => "620"  %>
            </div>
            <div>
              <div style="padding:10px;margin:5px;width:45%;float:left">
                <%= form_tag "/pages/submit" do %>
   
                  <label for="text"></label> <textarea id="text"  name="post"  rows="3" cols="35" class="required"></textarea>
                 <br/>
                 <%= params[:error_post] %> <br/>
                  <input type="submit" value="Post"/>
                  
              <%end%>
            </div>
              <% for post in @page_posts %>
                <div  style="background-color: white;margin:10px;width:45%;float:left">
                  <%= post.content %>
                  <br/><br/>
                  likes: <%= post.likes %>
                  <div style="background-color: white; padding-top:5px;padding-left:5px;padding-bottom:5px;padding-right:5px;">
                    <% comments = PostComment.find_by_sql("select * from post_comments where post_id="+post.id.to_s) %>
                    <% for comment in comments %>
                      <div style="background-color: grey;padding-top:5px;padding-left:5px;padding-bottom:5px;padding-right:5px;margin-bottom:5px">
                        <%= comment.comment%><br/>
                        likes: <%= comment.likes %>
                      </div>
                    <% end %>
                    <%= form_tag "/pages/comment" do %>
                         <label for="text"></label> <textarea id="text"name="comment" ></textarea>
                         <%= hidden_field_tag 'post_id', post.id %>
                         <input type="submit" value="comment"/> 
                    <%end%>
                  </div>
                </div>
                <br/>
              <%end%>
                
      </div>
      <div style="padding:20px;">
                
      </div>
  </div>



  <div>


 <%= button_to  @is_liked, {:action => "pageLike", :is_liked => @is_liked, :id => params[:id]},:class => 'btn btn-default btn-primary btn-lg' %>
<%if @page.admin_id.to_s==cookies[:user_id].to_s %>
<%= link_to 'Edit', edit_page_path(@page) %> 
<% end %>
<div class="bs-example">
    <div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Description</a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <p><%= @page.description%></p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">Likes (<%= @page.like%>)</a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <p>
          <% @liked_by = PagesLike.find_by_sql("select * from pages_likes where page_id="+@page.id.to_s) %>
          <% for @like in @liked_by %>
            <% user = User.find(@like.user_id) %>
             <a href= <%= "/main/profile?id="+user.id.to_s %> > <%= image_tag  user.profile_pic.url, :height => "50",:width => "50" %></a>
          <%end %>
        </p>
      </div>
    </div>
  </div>
  
</div>
</div>
  </div>
















 